trigger:
- main

pool:
  name: default
  
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
      containerRegistry: 'AsenSKDockReg'
      command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'AsenSKDockReg'
    repository: 'DevOpsTest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'